### ISSUE TITLE
How to download the metadata?

### ISSUE THREAD

**Issue by zhangpicb** [yupenghe/encode_dna_dynamics#1]
Hi

Thanks for the awesome codes for the beautiful figures.

I met a problem when I want to run the run_WGCNA.r script.I didn't find the AllDCCData_e10p5remapdDCCIndx_TPMs_Mtrx.txt. What should I do to solve this problem?

Thanks!

**Comment by yupenghe** [comment]
The file has been uploaded to this repository under `data/`.

https://github.com/yupenghe/encode_dna_dynamics/tree/master/data

**Comment by zhangpicb** [comment]
> The file has been uploaded to this repository under `data/`.
> 
> https://github.com/yupenghe/encode_dna_dynamics/tree/master/data

Thank you very much!

I also didn't find All_AllSmplsFull_ENCODESamples_FinalCodes_SampleTraitsReOrdrd_Clean.csv. How to download all metadatas?Maybe I missed or I didn't find the important url to download data.

Thanks!

**Comment by yupenghe** [comment]
Please find the file in the same link. 
https://github.com/yupenghe/encode_dna_dynamics/tree/master/data

I did not upload all the data to the repo due to file size concern. If you can send me a list of files needed, I can try to look for them.

**Comment by zhangpicb** [comment]
> Please find the file in the same link.
> https://github.com/yupenghe/encode_dna_dynamics/tree/master/data
> 
> I did not upload all the data to the repo due to file size concern. If you can send me a list of files needed, I can try to look for them.

Thanks!
